# Tab 1
new_tab Land
cd ~
launch zsh

# Tab 2
new_tab Codes
cd ~/Code
launch zsh

# Tab 3
new_tab Workspace
launch zsh

# Tab
# new_tab CoCo
# cd /run/media/orion13/462a8a2a-e1eb-4be8-bf37-e54cfe0eb3b4/github
# launch zsh

# Tab 4
new_tab Meh
cd ~/Code_PG
launch zsh